import Head from 'next/head'
import Image from 'next/image'
import { HeroSection, PoolAdd, PoolConnect } from '../components'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>JustSwap | Way You Swap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://user-images.githubusercontent.com/86917304/204307859-2d57a269-26c9-470b-8fd0-3a19a5ad0744.png" />
      </Head>
      <HeroSection />
    </div>
  )
}
